### ISSUE TITLE
feature: we need debian gnu toolchain support for debian buster 

### ISSUE THREAD

**Issue by osevan** [stoneatom/stonedb#163]
I see now you compiling with gcc 7.3, this is big fail.

Debian buster universe is using 10.2.1

I hope you can fix this dependency. 

Because installing more than one gcc is always fail on system, with newer librarys and future compilations

I hope you can install on debian buster vm your stonedb with default gcc toolchain and needed dependencys and update us here.

I want test as fast as possible your stonedb with sysbench and show your my results with tuned mariadb setup.

Thanks and

Best regards

**Comment by hustjieke** [comment]
We are working on upgrading gcc to support higher gcc version https://github.com/stoneatom/stonedb/issues/12
, there are still some remaining problems and will be resolved  soon.

Or you can compile stonedb in docker or just run it, we provide both two methods in order to make the user experience more convenient:  https://github.com/stoneatom/stonedb#build-stonedb-from-source-code-in-a-docker-container

Further more,  thanks for following our project!

**Comment by haitaoguan** [comment]
I have compiled StoneDB on Debian 10.The dependency packages required are the same as Ubuntu 20.04。
https://stonedb.io/docs/developer-guide/compiling-methods/compile-using-ubuntu20.04

PRETTY_NAME="Debian GNU/Linux 10 (buster)"

**Comment by RingsC** [comment]
@osevan , we have updated the compiling guide, pls check the latest out and try it again. Therefore, we close it now, and feel free to reopen it again if you are need it.
