### ISSUE TITLE
Does it support OLTP+OLAP+VectorDb, an integrated solution?

### ISSUE THREAD

**Issue by Qoooooooooooo** [stoneatom/stonedb#1973]
AI direction

**Comment by Nliver** [comment]
> AI direction
@Qoooooooooooo 
I am glad that you have raised this question to us. First of all, I would like to give you a positive reply that we can support it.

At present, StoneDB multi-warehouse version has been supported, and StoneDB stand-alone version also has relevant planning, because we noticed that the mainstream databases in the industry have begun to gradually support the function of vector computing, such as PostgreSQL, Oracle, etc., our StoneDB will also support this function in the future.

Could you tell me your specific use scenario? I think this will help us to further analyze and plan the follow-up research and development route.
